//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semana10.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NeptunoEntities : DbContext
    {
        public NeptunoEntities()
            : base("name=NeptunoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<categorias> categorias { get; set; }
        public DbSet<clientes> clientes { get; set; }
        public DbSet<compañiasdeenvios> compañiasdeenvios { get; set; }
        public DbSet<Empleados> Empleados { get; set; }
        public DbSet<Pedidos> Pedidos { get; set; }
        public DbSet<productos> productos { get; set; }
        public DbSet<proveedores> proveedores { get; set; }
        public DbSet<detallesdepedidos> detallesdepedidos { get; set; }
    }
}
